DROP DATABASE IF EXISTS QuanLyHocvien;
CREATE DATABASE QuanLyHocvien;
USE QuanLyHocvien;

CREATE TABLE Hocvien
(
	ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`Name` VARCHAR(30) NOT NULL,
    `Code` CHAR(5) NOT NULL UNIQUE,
    ModifiedDate TIMESTAMP
);
